# Generated by Django 4.2.4 on 2023-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="task",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
