# Generated by Django 4.2.4 on 2023-08-22 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_web", "0002_task_deadline_alter_task_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="name",
        ),
    ]
