# Generated by Django 4.2.4 on 2023-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_web", "0003_alter_task_options_remove_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
